### ISSUE TITLE
Mode must be changeable with a non-interactive command line

### ISSUE THREAD

**Issue by BiggerNoise** [ThirdCorner/scaffi-server-core#2]
This affects build servers running without human interaction.

I'm working around this by copying a prototype config file (scaffi-ui.private.development.json) to scaffi-ui.private.json. Seems a wee bit clunky.

**Comment by jblaketc** [comment]
Does it allow passing in flag arguments? We can add those to the generators
so you can bypass the GUI.

**Comment by BiggerNoise** [comment]
Yes. You can pass arguments to command line tools.

**Comment by jblaketc** [comment]
Implemented and pushed
